<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/styles.css'))
            ->prependStylesheet($this->basePath('vendor/fontawesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('vendor/themify-icons/themify-icons.min.css'))
            ->prependStylesheet($this->basePath('vendor/animate.css/animate.min.css'))
            ->prependStylesheet($this->basePath('vendor/perfect-scrollbar/perfect-scrollbar.min.css'))
            ->prependStylesheet($this->basePath('vendor/switchery/switchery.min.css'))
            ->prependStylesheet($this->basePath('vendor/bootstrap/css/bootstrap.min.css' ))
            ->prependStylesheet($this->basePath('css/theme-1.css','id="skin_color"'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/plugins.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('vendor/bootstrap/js/bootstrap.min.js'))
                ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))
                ->prependFile($this->basePath('vendor/modernizr/modernizr.js'))
                ->prependFile($this->basePath('vendor/perfect-scrollbar/perfect-scrollbar.min.js'))
                ->prependFile($this->basePath('vendor/switchery/switchery.min.js'))
                ->prependFile($this->basePath('js/main.js'))
                ->prependFile($this->basePath('js/index.js'))

                ->prependFile($this->basePath('vendor/jquery-cookie/jquery.cookie.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div id="app">
        <!-- sidebar -->
        <div class="sidebar app-aside" id="sidebar">
            <div class="sidebar-container perfect-scrollbar">
                <nav>
                    <!-- start: SEARCH FORM -->
                    <div class="search-form">
                        <a class="s-open" href="#">
                            <i class="ti-search"></i>
                        </a>
                        <form class="navbar-form" role="search">
                            <a class="s-remove" href="#" target=".navbar-form">
                                <i class="ti-close"></i>
                            </a>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Buscar...">
                                <button class="btn search-button" type="submit">
                                    <i class="ti-search"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                    <!-- end: SEARCH FORM -->
                    <!-- start: MAIN NAVIGATION MENU -->
                    <!--<div class="navbar-title">
                        <span>Main Navigation</span>
                    </div>-->
                    <ul class="main-navigation-menu">
                        <li>
                            <a href="index.html">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-home"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Cursos </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <!--<li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-settings"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> UI Elements </span><i class="icon-arrow"></i>
                                    </div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="ui_elements.html">
                                        <span class="title"> Elements </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_buttons.html">
                                        <span class="title"> Buttons </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_links.html">
                                        <span class="title"> Links </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_icons.html">
                                        <span class="title"> Font Awesome Icons </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_line_icons.html">
                                        <span class="title"> Linear Icons </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_modals.html">
                                        <span class="title"> Modals </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_toggle.html">
                                        <span class="title"> Toggle </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_tabs_accordions.html">
                                        <span class="title"> Tabs &amp; Accordions </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_panels.html">
                                        <span class="title"> Panels </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_notifications.html">
                                        <span class="title"> Notifications </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_treeview.html">
                                        <span class="title"> Treeview </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_media.html">
                                        <span class="title"> Media Object </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_nestable.html">
                                        <span class="title"> Nestable List </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="ui_typography.html">
                                        <span class="title"> Typography </span>
                                    </a>
                                </li>
                            </ul>
                        </li>-->
                        <!--<li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-layout-grid2"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Tables </span><i class="icon-arrow"></i>
                                    </div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="table_basic.html">
                                        <span class="title">Basic Tables</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="table_responsive.html">
                                        <span class="title">Responsive Tables</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="table_data.html">
                                        <span class="title">Advanced Data Tables</span>
                                    </a>
                                </li>
                            </ul>
                        </li>-->
                        <li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-pencil-alt"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Tutores </span><!--<i class="icon-arrow"></i>-->
                                    </div>
                                </div>
                            </a>
                            <!--<ul class="sub-menu">
                                <li>
                                    <a href="form_elements.html">
                                        <span class="title">Form Elements</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="form_text_editor.html">
                                        <span class="title">Text Editor</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="form_wizard.html">
                                        <span class="title">Form Wizard</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="form_validation.html">
                                        <span class="title">Form Validation</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="form_image_cropping.html">
                                        <span class="title">Image Cropping</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="form_multiple_upload.html">
                                        <span class="title">Multiple File Upload</span>
                                    </a>
                                </li>
                            </ul>-->
                        </li>
                        <li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-user"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Alumnos </span><!--<i class="icon-arrow"></i>-->
                                    </div>
                                </div>
                            </a>
                            <!--<ul class="sub-menu">
                                <li>
                                    <a href="login_signin.html">
                                        <span class="title"> Login Form </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="login_registration.html">
                                        <span class="title"> Registration Form </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="login_forgot.html">
                                        <span class="title"> Forgot Password Form </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="login_lockscreen.html">
                                        <span class="title">Lock Screen</span>
                                    </a>
                                </li>
                            </ul>-->
                        </li>
                        <!--<li class="active open">
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-layers-alt"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Pages </span><i class="icon-arrow"></i>
                                    </div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="pages_user_profile.html">
                                        <span class="title">User Profile</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="pages_invoice.html">
                                        <span class="title">Invoice</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="pages_timeline.html">
                                        <span class="title">Timeline</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="pages_calendar.html">
                                        <span class="title">Calendar</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="pages_messages.html">
                                        <span class="title">Messages</span>
                                    </a>
                                </li>
                                <li class="active">
                                    <a href="pages_blank_page.html">
                                        <span class="title">Blank Page</span>
                                    </a>
                                </li>
                            </ul>
                        </li>-->
                        <!--<li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-package"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Utilities </span><i class="icon-arrow"></i>
                                    </div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="utilities_search_result.html">
                                        <span class="title">Search Results</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="utilities_error_404.html">
                                        <span class="title">Error 404</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="utilities_error_500.html">
                                        <span class="title">Error 500</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="utilities_pricing_table.html">
                                        <span class="title">Pricing Table</span>
                                    </a>
                                </li>
                            </ul>
                        </li>-->
                        <!--<li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-folder"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> 3 Level Menu </span><i class="icon-arrow"></i>
                                    </div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="javascript:;">
                                        <span>Item 1</span> <i class="icon-arrow"></i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="#">
                                                Sample Link 1
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Sample Link 2
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Sample Link 3
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span>Item 2</span> <i class="icon-arrow"></i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="#">
                                                Sample Link 1
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Sample Link 2
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Sample Link 3
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span>Item 3</span> <i class="icon-arrow"></i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="#">
                                                Sample Link 1
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Sample Link 2
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Sample Link 3
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>-->
                        <li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-menu-alt"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Medidas </span><i class="icon-arrow"></i>
                                    </div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="javascript:;">
                                        <span>Item 1</span> <i class="icon-arrow"></i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 1</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 2</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 3</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span>Item 2</span> <i class="icon-arrow"></i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 1</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 2</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 3</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span>Item 3</span> <i class="icon-arrow"></i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 1</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 2</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span>Sample Link 3</span> <i class="icon-arrow"></i>
                                            </a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="#">
                                                        Sample Link 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        Sample Link 3
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <!--<li>
                            <a href="maps.html">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-location-pin"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Maps </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="charts.html">
                                <div class="item-content">
                                    <div class="item-media">
                                        <i class="ti-pie-chart"></i>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Charts </span>
                                    </div>
                                </div>
                            </a>
                        </li>-->
                    </ul>
                    <!-- end: MAIN NAVIGATION MENU -->
                    <!-- start: CORE FEATURES -->
                    <!--<div class="navbar-title">
                        <span>Core Features</span>
                    </div>
                    <ul class="folders">
                        <li>
                            <a href="pages_calendar.html">
                                <div class="item-content">
                                    <div class="item-media">
                                        <span class="fa-stack"> <i class="fa fa-square fa-stack-2x"></i> <i class="fa fa-terminal fa-stack-1x fa-inverse"></i> </span>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Calendar </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="pages_messages.html">
                                <div class="item-content">
                                    <div class="item-media">
                                        <span class="fa-stack"> <i class="fa fa-square fa-stack-2x"></i> <i class="fa fa-folder-open-o fa-stack-1x fa-inverse"></i> </span>
                                    </div>
                                    <div class="item-inner">
                                        <span class="title"> Messages </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>-->
                    <!-- end: CORE FEATURES -->
                    <!-- start: DOCUMENTATION BUTTON -->
                    <!--<div class="wrapper">
                        <a href="documentation.html" class="button-o">
                            <i class="ti-help"></i>
                            <span>Documentation</span>
                        </a>
                    </div>-->
                    <!-- end: DOCUMENTATION BUTTON -->
                </nav>
            </div>
        </div>
        <!-- / sidebar -->
        <div class="app-content">
            <!-- start: TOP NAVBAR -->
            <header class="navbar navbar-default navbar-static-top">
                <!-- start: NAVBAR HEADER -->
                <div class="navbar-header">
                    <a href="#" class="sidebar-mobile-toggler pull-left hidden-md hidden-lg" class="btn btn-navbar sidebar-toggle" data-toggle-class="app-slide-off" data-toggle-target="#app" data-toggle-click-outside="#sidebar">
                        <i class="ti-align-justify"></i>
                    </a>
                    <a class="navbar-brand" href="#">
                        <!--<img src="assets/images/logo.png" alt="Clip-Two"/>-->
                        <p>Gestion Alumnos</p>
                    </a>
                    <a href="#" class="sidebar-toggler pull-right visible-md visible-lg" data-toggle-class="app-sidebar-closed" data-toggle-target="#app">
                        <i class="ti-align-justify"></i>
                    </a>
                    <a class="pull-right menu-toggler visible-xs-block" id="menu-toggler" data-toggle="collapse" href=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="ti-view-grid"></i>
                    </a>
                </div>
                <!-- end: NAVBAR HEADER -->
                <!-- start: NAVBAR COLLAPSE -->
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-right">
                        <!-- start: MESSAGES DROPDOWN -->
                        <!--<li class="dropdown">
                            <a href class="dropdown-toggle" data-toggle="dropdown">
                                <span class="dot-badge partition-red"></span> <i class="ti-comment"></i> <span>MESSAGES</span>
                            </a>
                            <ul class="dropdown-menu dropdown-light dropdown-messages dropdown-large">
                                <li>
                                    <span class="dropdown-header"> Unread messages</span>
                                </li>
                                <li>
                                    <div class="drop-down-wrapper ps-container">
                                        <ul>
                                            <li class="unread">
                                                <a href="javascript:;" class="unread">
                                                    <div class="clearfix">
                                                        <div class="thread-image">
                                                            <img src="./assets/images/avatar-2.jpg" alt="">
                                                        </div>
                                                        <div class="thread-content">
                                                            <span class="author">Nicole Bell</span>
                                                            <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula...</span>
                                                            <span class="time"> Just Now</span>
                                                        </div>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;" class="unread">
                                                    <div class="clearfix">
                                                        <div class="thread-image">
                                                            <img src="./assets/images/avatar-3.jpg" alt="">
                                                        </div>
                                                        <div class="thread-content">
                                                            <span class="author">Steven Thompson</span>
                                                            <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula...</span>
                                                            <span class="time">8 hrs</span>
                                                        </div>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;">
                                                    <div class="clearfix">
                                                        <div class="thread-image">
                                                            <img src="./assets/images/avatar-5.jpg" alt="">
                                                        </div>
                                                        <div class="thread-content">
                                                            <span class="author">Kenneth Ross</span>
                                                            <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula...</span>
                                                            <span class="time">14 hrs</span>
                                                        </div>
                                                    </div>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="view-all">
                                    <a href="#">
                                        See All
                                    </a>
                                </li>
                            </ul>
                        </li>-->
                        <!-- end: MESSAGES DROPDOWN -->
                        <!-- start: NOTIFICATION DROPDOWN -->
                        <li class="dropdown">
                            <a href class="dropdown-toggle" data-toggle="dropdown">
                                <i class="ti-check-box"></i> <span>NOTIFICACIONES</span>
                            </a>
                            <ul class="dropdown-menu dropdown-light dropdown-messages dropdown-large">
                                <li>
                                    <span class="dropdown-header"> Tienes nuevas notificaciones</span>
                                </li>
                                <li>
                                    <div class="drop-down-wrapper ps-container">
                                        <div class="list-group no-margin">
                                            <a class="media list-group-item" href="">
                                                <img class="img-circle" alt="..." src="assets/images/avatar-1.jpg">
                                                <span class="media-body block no-margin"> Use awesome animate.css <small class="block text-grey">10 minutes ago</small> </span>
                                            </a>
                                            <a class="media list-group-item" href="">
                                                <span class="media-body block no-margin"> 1.0 initial released <small class="block text-grey">1 hour ago</small> </span>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                                <li class="view-all">
                                    <a href="#">
                                        See All
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- end: ACTIVITIES DROPDOWN -->
                        <!-- start: LANGUAGE SWITCHER -->
                        <li class="dropdown">
                            <a href class="dropdown-toggle" data-toggle="dropdown">
                                <i class="ti-world"></i> Español
                            </a>
                            <ul role="menu" class="dropdown-menu dropdown-light fadeInUpShort">
                                <li>
                                    <a href="#" class="menu-toggler">
                                        Deutsch
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="menu-toggler">
                                        English
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="menu-toggler">
                                        Italiano
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- start: LANGUAGE SWITCHER -->
                        <!-- start: USER OPTIONS DROPDOWN -->
                        <li class="dropdown current-user">
                            <a href class="dropdown-toggle" data-toggle="dropdown">
                                <span class="username">Orientador <i class="ti-angle-down"></i></i></span>
                            </a>
                            <ul class="dropdown-menu dropdown-dark">
                                <li>
                                    <a href="pages_user_profile.html">
                                        Mi Perfil
                                    </a>
                                </li>
                                <!--<li>
                                    <a href="pages_calendar.html">
                                        Mi calendario
                                    </a>
                                </li>
                                <li>
                                    <a hef="pages_messages.html">
                                        My Messages (3)
                                    </a>
                                </li>
                                <li>
                                    <a href="login_lockscreen.html">
                                        Lock Screen
                                    </a>
                                </li>-->
                                <li>
                                    <a href="login_signin.html">
                                        Cerrar Sesión
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- end: USER OPTIONS DROPDOWN -->
                    </ul>
                    <!-- start: MENU TOGGLER FOR MOBILE DEVICES -->
                    <div class="close-handle visible-xs-block menu-toggler" data-toggle="collapse" href=".navbar-collapse">
                        <div class="arrow-left"></div>
                        <div class="arrow-right"></div>
                    </div>
                    <!-- end: MENU TOGGLER FOR MOBILE DEVICES -->
                </div>
                <a class="dropdown-off-sidebar" data-toggle-class="app-offsidebar-open" data-toggle-target="#app" data-toggle-click-outside="#off-sidebar">
                    &nbsp;
                </a>
                <!-- end: NAVBAR COLLAPSE -->
            </header>
            <!-- end: TOP NAVBAR -->
            <div class="main-content">
                <div class="container">
                    <?php echo $this->content; ?>
                    <hr>
                    <footer>
                        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                    </footer>
                </div> <!-- /container -->
            </div>
            </div>
        </div>



        <?php
        $this->inlineScript()->prependFile($this->basePath('vendor/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))
            ->prependFile($this->basePath('vendor/modernizr/modernizr.js'))
            ->prependFile($this->basePath('vendor/perfect-scrollbar/perfect-scrollbar.min.js'))
            ->prependFile($this->basePath('vendor/switchery/switchery.min.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/index.js'))

            ->prependFile($this->basePath('vendor/jquery-cookie/jquery.cookie.js'));

        $this->inlineScript()->captureStart();
        echo <<<JS
   jQuery(document).ready(function() {
				Main.init();
			});
JS;
        $this->inlineScript()->captureEnd();

        echo $this->inlineScript();
        ?>
    </body>

</html>
